config/routes.rb
Artart::Application.routes.draw do
  devise_for :users

  resources :gallery_items

  resources :galleries

  resources :room_available_dates

  resources :rooms

  resources :room_type_featurings

  resources :room_type_features

  resources :room_types

  resources :hotel_featurings

  resources :hotel_features

  resources :hotels

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.roles.include?('admin')
      can :manage, :all
    else
      can :read, :all
      # can :create, Comment
      # can :update, Comment do |comment|
      #   comment.try(:user) == user || user.roles.include?('moderator')
      # end
    if user.roles.include?('moderator')
      can :create, GalleryItem
      can :update, GalleryItem
    end
      # if user.roles.include?('author')
      # can :create, Comment
      # can :update, Comment do |article|
      #   article.try(:user) == user
      # end
      # end
    end
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name, :galleriable_id, :galleriable_type
  
  belongs_to :galleriable, :polymorphic => true
  has_many :gallery_items
end

app/models/gallery_item.rb
class GalleryItem < ActiveRecord::Base
  #attr_accessible :name, :gallery_id
  
  belongs_to :gallery
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/gallery_items/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/gallery_items/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  #attr_accessible :name, :star, :description, :detail, :address, :website, :email, :phone, :fax, :longitude, :latitude
  
  has_many :hotel_featurings
  has_many :hotel_features, :through => :hotel_featurings
  
  has_one :gallery, :as => :galleriable
  
  has_attached_file :avatar, :styles => { :small => "150x150>", :avatar => "150x150#" },
                    :url  => "/assets/hotels/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/hotels/:id/:style/:basename.:extension"

  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  
  after_save do |hotel|
    gallery = Gallery.new
    gallery.galleriable = hotel
    gallery.name = "#{hotel.name}'s Gallery"
    gallery.save
  end
end

app/models/hotel_feature.rb
class HotelFeature < ActiveRecord::Base
  attr_accessible :name
  
  has_many :hotel_featurings
  has_many :hotels, :through => :hotel_featurings
end

app/models/hotel_featuring.rb
class HotelFeaturing < ActiveRecord::Base
  attr_accessible :hotel_id, :hotel_feature_id
  
  belongs_to :hotel
  belongs_to :hotel_feature
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :price, :room_type_id
end

app/models/room_available_date.rb
class RoomAvailableDate < ActiveRecord::Base
  attr_accessible :room_id, :begin_at, :end_at
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  attr_accessible :name, :description, :hotel_id
  
  has_many :room_type_featurings
  has_many :room_type_features, :through => :room_type_featurings
end

app/models/room_type_feature.rb
class RoomTypeFeature < ActiveRecord::Base
  attr_accessible :name
  
  has_many :room_type_featurings
  has_many :room_types, :through => :room_type_featurings
end

app/models/room_type_featuring.rb
class RoomTypeFeaturing < ActiveRecord::Base
  attr_accessible :room_type_id, :room_type_feature_id
  
  belongs_to :room_type
  belongs_to :room_type_feature
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles
  
  named_scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }
  
  ROLES = %w[admin moderator vip member]
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  
  def role_symbols
    roles.map(&:to_sym)
  end
end

app/controllers/room_available_dates_controller.rb
class RoomAvailableDatesController < ApplicationController
  def index
    @room_available_dates = RoomAvailableDate.all
  end
  
  def show
    @room_available_date = RoomAvailableDate.find(params[:id])
  end
  
  def new
    @room_available_date = RoomAvailableDate.new
  end
  
  def create
    @room_available_date = RoomAvailableDate.new(params[:room_available_date])
    if @room_available_date.save
      flash[:notice] = "Successfully created room available date."
      redirect_to @room_available_date
    else
      render :action => 'new'
    end
  end
  
  def edit
    @room_available_date = RoomAvailableDate.find(params[:id])
  end
  
  def update
    @room_available_date = RoomAvailableDate.find(params[:id])
    if @room_available_date.update_attributes(params[:room_available_date])
      flash[:notice] = "Successfully updated room available date."
      redirect_to @room_available_date
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @room_available_date = RoomAvailableDate.find(params[:id])
    @room_available_date.destroy
    flash[:notice] = "Successfully destroyed room available date."
    redirect_to room_available_dates_url
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(params[:room])
    if @room.save
      flash[:notice] = "Successfully created room."
      redirect_to @room
    else
      render :action => 'new'
    end
  end
  
  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(params[:room])
      flash[:notice] = "Successfully updated room."
      redirect_to @room
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "Successfully destroyed room."
    redirect_to rooms_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_items_helper.rb
module GalleryItemsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/room_available_dates_helper.rb
module RoomAvailableDatesHelper
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/room_available_dates/_form.html.erb
<%= form_for @room_available_date do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :room_id %><br />
    <%= f.text_field :room_id %>
  </p>
  <p>
    <%= f.label :begin_at %><br />
    <%= f.date_select :begin_at %>
  </p>
  <p>
    <%= f.label :end_at %><br />
    <%= f.date_select :end_at %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/room_available_dates/_room_available_date.html.erb
RoomId : <%= link_to room_available_date.room_id, room_available_date %><br />
Begin : <%= room_available_date.begin_at %> | 
End : <%= room_available_date.end_at %>

<p>
  <% if can? :update, RoomAvailableDate%>
    <%= link_to "Edit", edit_room_available_date_path(room_available_date) %>
  <% end %>
  <% if can? :destroy, RoomAvailableDate %>
    <%= link_to "Destroy", room_available_date, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</p>

<hr />

app/views/room_available_dates/edit.html.erb
<% title "Edit Room Available Date" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @room_available_date %> |
  <%= link_to "View All", room_available_dates_path %>
</p>

app/views/room_available_dates/index.html.erb
<% title "Room Available Dates" %>

<%= render @room_available_dates %>

<% if can? :create, RoomAvailableDate %>
  <p><%= link_to "New Room Available Date", new_room_available_date_path %></p>
<% end%>

app/views/room_available_dates/new.html.erb
<% title "New Room Available Date" %>

<%= render 'form' %>

<p><%= link_to "Back to List", room_available_dates_path %></p>

app/views/room_available_dates/show.html.erb
<% title "Room Available Date" %>

<p>
  <strong>Room:</strong>
  <%= @room_available_date.room_id %>
</p>
<p>
  <strong>Begin At:</strong>
  <%= @room_available_date.begin_at %>
</p>
<p>
  <strong>End At:</strong>
  <%= @room_available_date.end_at %>
</p>

<p>
  <% if can? :update, RoomAvailableDate%>
    <%= link_to "Edit", edit_room_available_date_path(@room_available_date) %>
  <% end %>
  <% if can? :destroy, RoomAvailableDate %>
    <%= link_to "Destroy", @room_available_date, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</p>

<%= link_to "Back to Room available dates", room_available_dates_path %>