config/routes.rb
Artart::Application.routes.draw do
  devise_for :users

  resources :gallery_items

  resources :galleries

  resources :room_available_dates

  resources :rooms

  resources :room_type_featurings

  resources :room_type_features

  resources :room_types

  resources :hotel_featurings

  resources :hotel_features

  resources :hotels

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/gallery_item.rb
class GalleryItem < ActiveRecord::Base
  #attr_accessible :name, :gallery_id
  
  belongs_to :gallery
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/gallery_items/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/gallery_items/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/gallery_items_controller.rb
class GalleryItemsController < ApplicationController
  
  load_and_authorize_resource
  
  def index
    @gallery_items = GalleryItem.all
  end
  
  def show
    @gallery_item = GalleryItem.find(params[:id])
  end
  
  def new
    @gallery_item = GalleryItem.new
  end
  
  def create
    @gallery_item = GalleryItem.new(params[:gallery_item])
    if @gallery_item.save
      flash[:notice] = "Successfully created gallery item."
      redirect_to @gallery_item.gallery
    else
      render :action => 'new'
    end
  end
  
  def edit
    @gallery_item = GalleryItem.find(params[:id])
  end
  
  def update
    @gallery_item = GalleryItem.find(params[:id])
    if @gallery_item.update_attributes(params[:gallery_item])
      flash[:notice] = "Successfully updated gallery item."
      redirect_to @gallery_item
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @gallery = @gallery_item.gallery
    @gallery_item = GalleryItem.find(params[:id])
    @gallery_item.destroy
    flash[:notice] = "Successfully destroyed gallery item."
    redirect_to @gallery
  end
end

app/helpers/gallery_items_helper.rb
module GalleryItemsHelper
end

app/views/gallery_items/_form.html.erb
<%= form_for @gallery_item, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </p>
  
  <p><%= f.submit %></p>
  
  <%= f.hidden_field :gallery_id %>
<% end %>

app/views/gallery_items/_gallery_item.html.erb
Name : <%= link_to gallery_item.name, gallery_item %> | 
GalleryId : <%= gallery_item.gallery_id %>

<p>
  <% if can? :create, GalleryItem %>
    <%= link_to "Edit", edit_gallery_item_path(gallery_item) %>
  <% end %>
  <% if can? :destroy, GalleryItem %>
    <%= link_to "Destroy", gallery_item, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</p>

app/views/gallery_items/edit.html.erb
<% title "Edit Gallery Item" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @gallery_item %> |
  <%= link_to "View All", gallery_items_path %>
</p>

app/views/gallery_items/index.html.erb
<% title "Gallery Items" %>

<%= render @gallery_items %>

<% if can? :create, GalleryItem %>
  <p><%= link_to "New Gallery Item", new_gallery_item_path %></p>
<% end %>

app/views/gallery_items/new.html.erb
<% title "New Gallery Item" %>

<%= render 'form' %>

<p><%= link_to "Back to List", gallery_items_path %></p>

app/views/gallery_items/show.html.erb
<% title "Gallery Item" %>

<p>
  <strong>Name:</strong>
  <%= @gallery_item.name %>
</p>
<p>
  <strong>Gallery:</strong>
  <%= @gallery_item.gallery_id %>
</p>
<p>
  <strong>Photo:</strong>
  <%= image_tag @gallery_item.photo.url(:small) %>
</p>

<p>
  <% if can? :update, GalleryItem %>
    <%= link_to "Edit", edit_gallery_item_path(@gallery_item) %> |
  <% end %>
  <% if can? :destroy, GalleryItem %>
    <%= link_to "Destroy", @gallery_item, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</p>

<%= link_to "Back to Gallery Items", gallery_items_path %>