config/routes.rb
Artart::Application.routes.draw do
  devise_for :users

  resources :gallery_items

  resources :galleries

  resources :room_available_dates

  resources :rooms

  resources :room_type_featurings

  resources :room_type_features

  resources :room_types

  resources :hotel_featurings

  resources :hotel_features

  resources :hotels

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.roles.include?('admin')
      can :manage, :all
    else
      can :read, :all
      # can :create, Comment
      # can :update, Comment do |comment|
      #   comment.try(:user) == user || user.roles.include?('moderator')
      # end
    if user.roles.include?('moderator')
      can :create, GalleryItem
      can :update, GalleryItem
    end
      # if user.roles.include?('author')
      # can :create, Comment
      # can :update, Comment do |article|
      #   article.try(:user) == user
      # end
      # end
    end
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name, :galleriable_id, :galleriable_type
  
  belongs_to :galleriable, :polymorphic => true
  has_many :gallery_items
end

app/models/gallery_item.rb
class GalleryItem < ActiveRecord::Base
  #attr_accessible :name, :gallery_id
  
  belongs_to :gallery
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/gallery_items/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/gallery_items/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  #attr_accessible :name, :star, :description, :detail, :address, :website, :email, :phone, :fax, :longitude, :latitude
  
  has_many :hotel_featurings
  has_many :hotel_features, :through => :hotel_featurings
  
  has_one :gallery, :as => :galleriable
  
  has_attached_file :avatar, :styles => { :small => "150x150>", :avatar => "150x150#" },
                    :url  => "/assets/hotels/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/hotels/:id/:style/:basename.:extension"

  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  
  after_save do |hotel|
    gallery = Gallery.new
    gallery.galleriable = hotel
    gallery.name = "#{hotel.name}'s Gallery"
    gallery.save
  end
end

app/models/hotel_feature.rb
class HotelFeature < ActiveRecord::Base
  attr_accessible :name
  
  has_many :hotel_featurings
  has_many :hotels, :through => :hotel_featurings
end

app/models/hotel_featuring.rb
class HotelFeaturing < ActiveRecord::Base
  attr_accessible :hotel_id, :hotel_feature_id
  
  belongs_to :hotel
  belongs_to :hotel_feature
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :price, :room_type_id
end

app/models/room_available_date.rb
class RoomAvailableDate < ActiveRecord::Base
  attr_accessible :room_id, :begin_at, :end_at
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  attr_accessible :name, :description, :hotel_id
  
  has_many :room_type_featurings
  has_many :room_type_features, :through => :room_type_featurings
end

app/models/room_type_feature.rb
class RoomTypeFeature < ActiveRecord::Base
  attr_accessible :name
  
  has_many :room_type_featurings
  has_many :room_types, :through => :room_type_featurings
end

app/models/room_type_featuring.rb
class RoomTypeFeaturing < ActiveRecord::Base
  attr_accessible :room_type_id, :room_type_feature_id
  
  belongs_to :room_type
  belongs_to :room_type_feature
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles
  
  named_scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }
  
  ROLES = %w[admin moderator vip member]
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  
  def role_symbols
    roles.map(&:to_sym)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  
  load_and_authorize_resource
  
  def index
    @hotels = Hotel.all
  end
  
  def show
    @hotel = Hotel.find(params[:id])
    if !@hotel.gallery
      @gallery = Gallery.new
      @gallery.galleriable = @hotel
      @gallery.name = "#{@hotel.name}'s Gallery"
      @gallery.save
      @hotel = Hotel.find(params[:id])
    end    
  end
  
  def new
    @hotel = Hotel.new
  end
  
  def create
    @hotel = Hotel.new(params[:hotel])
    if @hotel.save
      flash[:notice] = "Successfully created hotel."
      redirect_to @hotel
    else
      render :action => 'new'
    end
  end
  
  def edit
    @hotel = Hotel.find(params[:id])
  end
  
  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update_attributes(params[:hotel])
      flash[:notice] = "Successfully updated hotel."
      redirect_to @hotel
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    flash[:notice] = "Successfully destroyed hotel."
    redirect_to hotels_url
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(params[:room])
    if @room.save
      flash[:notice] = "Successfully created room."
      redirect_to @room
    else
      render :action => 'new'
    end
  end
  
  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(params[:room])
      flash[:notice] = "Successfully updated room."
      redirect_to @room
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "Successfully destroyed room."
    redirect_to rooms_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_items_helper.rb
module GalleryItemsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hotels/_form.html.erb
<%= form_for @hotel, :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :star %><br />
    <%= f.text_field :star %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :detail %><br />
    <%= f.text_area :detail %>
  </p>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :fax %><br />
    <%= f.text_field :fax %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/hotels/_gallery.html.erb
<div class="gallery" style="border-bottom: 1px solid #DDD; padding: 10px;">
  <h2><%= link_to gallery.name, gallery %></h2>

  <p>
    <% if can? :update, Gallery %>
      <%= link_to "edit gallery", gallery %> | 
    <% end %>
    <% if can? :destroy, Gallery %>
      <%= link_to "Destroy", gallery, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  </p>

  <ul id="gallery">
    <% gallery.gallery_items.each do |gallery_item| %>
      <%= link_to image_tag(gallery_item.photo.url(:small)), gallery_item.photo.url, :title => gallery_item.name %>
      <%#= image_tag gallery_item.photo.url(:small)%><br/>
    <% end%>
  </ul>
</div>

app/views/hotels/_hotel.html.erb
<div class="hotel">
  <div id="hotel_avatar">
  <% if hotel.avatar? %>
    <%= link_to(image_tag(hotel.avatar.url(:avatar)), hotel) %>
  <% else %>
    <%= link_to(image_tag("/images/rails.png"), hotel) %>
  <% end %>
  </div>
  
  <div id="hotel_content">
    <h2><%= link_to hotel.name, hotel %></h2>
    <b>Star : </b> <%= hotel.star %>
    <b>Phone : </b> <%= hotel.phone %>
    
    <p>
      <%= hotel.description %><br />
      <% if can? :update, Hotel %>
        <%= link_to "Edit", edit_hotel_path(hotel) %> | 
      <% end %>
      <% if can? :destroy, Hotel %>
        <%= link_to "Destroy", hotel, :confirm => 'Are you sure?', :method => :delete %>
      <% end %>
    </p>
  </div>

</div>

app/views/hotels/edit.html.erb
<% title "Edit Hotel" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @hotel %> |
  <%= link_to "View All", hotels_path %>
</p>

app/views/hotels/index.html.erb
<% title "Hotels" %>

<%= render @hotels %>

<% if can? :create, Hotel %>
  <p><%= link_to "New Hotel", new_hotel_path %></p>
<% end %>

app/views/hotels/new.html.erb
<% title "New Hotel" %>

<%= render 'form' %>

<p><%= link_to "Back to List", hotels_path %></p>

app/views/hotels/show.html.erb
<% title "Hotel" %>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>
<p>
  <strong>Star:</strong>
  <%= @hotel.star %>
</p>
<p>
  <strong>Description:</strong>
  <%= @hotel.description %>
</p>
<p>
  <strong>Detail:</strong>
  <%= @hotel.detail %>
</p>
<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>
<p>
  <strong>Website:</strong>
  <%= @hotel.website %>
</p>
<p>
  <strong>Email:</strong>
  <%= @hotel.email %>
</p>
<p>
  <strong>Phone:</strong>
  <%= @hotel.phone %>
</p>
<p>
  <strong>Fax:</strong>
  <%= @hotel.fax %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @hotel.longitude %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @hotel.latitude %>
</p>

<% if @hotel.gallery %>
  
  <h3><%= @hotel.name%>'s Gallery</h3>
  
  <% if !(@hotel.gallery.gallery_items == []) %>
    <%= render :partial => '/hotels/gallery', :locals => {:gallery => @hotel.gallery} %>
  <% else %>
    <% if can? :update, Gallery %>
      <p>Don't have any photos <%= link_to "Add Photo", @hotel.gallery %></p>
    <% else %>
      <p>Don't have any photos</p>
    <% end %>
  <% end %>

<% else %>

  <%= render :partial => '/galleries/form' %>

<% end %>

<p>
  <% if can? :update, Hotel %>
    <%= link_to "Edit", edit_hotel_path(@hotel) %> | 
  <% end %>
  <% if can? :destroy, Hotel %>
    <%= link_to "Destroy", @hotel, :confirm => 'Are you sure?', :method => :delete %>
  <% end %>
</p>

<%= link_to "Back to Hotels", hotels_path %>