config/routes.rb
Artart::Application.routes.draw do
  devise_for :users

  resources :gallery_items

  resources :galleries

  resources :room_available_dates

  resources :rooms

  resources :room_type_featurings

  resources :room_type_features

  resources :room_types

  resources :hotel_featurings

  resources :hotel_features

  resources :hotels

  get "welcome/index"

  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
    user ||= User.new # guest user
    
    if user.roles.include?('admin')
      can :manage, :all
    else
      can :read, :all
      # can :create, Comment
      # can :update, Comment do |comment|
      #   comment.try(:user) == user || user.roles.include?('moderator')
      # end
    if user.roles.include?('moderator')
      can :create, GalleryItem
      can :update, GalleryItem
    end
      # if user.roles.include?('author')
      # can :create, Comment
      # can :update, Comment do |article|
      #   article.try(:user) == user
      # end
      # end
    end
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name, :galleriable_id, :galleriable_type
  
  belongs_to :galleriable, :polymorphic => true
  has_many :gallery_items
end

app/models/gallery_item.rb
class GalleryItem < ActiveRecord::Base
  #attr_accessible :name, :gallery_id
  
  belongs_to :gallery
  
  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/gallery_items/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/gallery_items/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  #attr_accessible :name, :star, :description, :detail, :address, :website, :email, :phone, :fax, :longitude, :latitude
  
  has_many :hotel_featurings
  has_many :hotel_features, :through => :hotel_featurings
  
  has_one :gallery, :as => :galleriable
  
  has_attached_file :avatar, :styles => { :small => "150x150>", :avatar => "150x150#" },
                    :url  => "/assets/hotels/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/hotels/:id/:style/:basename.:extension"

  validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
  
  after_save do |hotel|
    gallery = Gallery.new
    gallery.galleriable = hotel
    gallery.name = "#{hotel.name}'s Gallery"
    gallery.save
  end
end

app/models/hotel_feature.rb
class HotelFeature < ActiveRecord::Base
  attr_accessible :name
  
  has_many :hotel_featurings
  has_many :hotels, :through => :hotel_featurings
end

app/models/hotel_featuring.rb
class HotelFeaturing < ActiveRecord::Base
  attr_accessible :hotel_id, :hotel_feature_id
  
  belongs_to :hotel
  belongs_to :hotel_feature
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :price, :room_type_id
end

app/models/room_available_date.rb
class RoomAvailableDate < ActiveRecord::Base
  attr_accessible :room_id, :begin_at, :end_at
end

app/models/room_type.rb
class RoomType < ActiveRecord::Base
  attr_accessible :name, :description, :hotel_id
  
  has_many :room_type_featurings
  has_many :room_type_features, :through => :room_type_featurings
end

app/models/room_type_feature.rb
class RoomTypeFeature < ActiveRecord::Base
  attr_accessible :name
  
  has_many :room_type_featurings
  has_many :room_types, :through => :room_type_featurings
end

app/models/room_type_featuring.rb
class RoomTypeFeaturing < ActiveRecord::Base
  attr_accessible :room_type_id, :room_type_feature_id
  
  belongs_to :room_type
  belongs_to :room_type_feature
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :roles
  
  named_scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }
  
  ROLES = %w[admin moderator vip member]
  
  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end
  
  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end
  
  def role_symbols
    roles.map(&:to_sym)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end
  
  def show
    @room = Room.find(params[:id])
  end
  
  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(params[:room])
    if @room.save
      flash[:notice] = "Successfully created room."
      redirect_to @room
    else
      render :action => 'new'
    end
  end
  
  def edit
    @room = Room.find(params[:id])
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(params[:room])
      flash[:notice] = "Successfully updated room."
      redirect_to @room
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "Successfully destroyed room."
    redirect_to rooms_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_items_helper.rb
module GalleryItemsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/room_types_helper.rb
module RoomTypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "reset", "lightbox/jquery.lightbox-0.5", "app", "content" %>
    <%= javascript_include_tag "jquery", "jquery.rails", "lightbox/jquery.lightbox-0.5.pack", "application" %>    
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    
    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path %>
          <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
        <% end %>
      </div><!-- #user_nav -->
          
      <div id="header">
        
        
          
        <ul id="tabs">
          <li><%= link_to "Hotel", hotels_path %></li>
          <li><%= link_to "HotelFeature", hotel_features_path %></li>
          <li><%= link_to "RoomType", room_types_path %></li>
          <li><%= link_to "RoomTypeFeature", room_type_features_path %></li>
          <li><%= link_to "Room", rooms_path %></li>
          <li><%= link_to "RoomAvailableDate", room_available_dates_path %></li>
          <li><%= link_to "Gallery", galleries_path %></li>
          <li><%= link_to "GalleryItem", gallery_items_path %></li>
        </ul><!-- #tabs -->
        
      </div><!-- #header -->
      
      <div id="body">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        <% end %>
        
        <%= content_tag :h1, yield(:title) if show_title? %>
        
        <%= yield %>
        
      </div><!-- #body -->
      
      <div id="foot">
        BookingEverything@bookingeverything.com by CanonX
      </div><!-- #foot -->
      
    </div>
  </body>
</html>